CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) UNIQUE,
  given_name VARCHAR(35),
  last_name VARCHAR(35),
  password VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS listings (
  id INT NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  title VARCHAR(50) NOT NULL,
  description VARCHAR(255) NOT NULL,
  salary DECIMAL(8,2) NOT NULL,
  tags VARCHAR(255),
  company VARCHAR(100) NOT NULL,
  address VARCHAR(255) NOT NULL,
  city VARCHAR(50) NOT NULL,
  state VARCHAR(50) NOT NULL,
  phone VARCHAR(15) NOT NULL,
  email VARCHAR(80) NOT NULL,
  requirements VARCHAR(255) NOT NULL,
  benefits VARCHAR(255),
  PRIMARY KEY (id),
  CONSTRAINT fk_listings_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
);